# Generated by Django 3.2.8 on 2021-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of publisher.', max_length=50)),
                ('website', models.URLField(help_text="The publisher's website.")),
                ('email', models.EmailField(help_text="The publisher's email address.", max_length=254)),
            ],
        ),
    ]
